version: '3'
services:
  web:
    build: ./
    image: testflask:latest
    volumes:
      - ./app:/app
    ports:
      - "8082:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    env_file:
      - .env
    networks:
      - vtools_network
   
networks:
  vtools_network:
    external: true