version: '3'


services:
    vtools_web:
      build:
        context: .
      image: vtools_web:latest
      environment:
        - WORK_FOLDER=/home/
        - PROJECT_FOLDER=/home/testProject/
      volumes:
        - ${REFERENCE_FOLDER}:/home/app/.variant_tools/
        - ${PROJECT_FOLDER}:/home/testProject/
      labels:
        - "traefik.enable=true"
        - "traefik.backend=flask"
        - "traefik.frontend.rule=Host:collabondata.com"
        - "traefik.domain=localhost:8087/vtools/"
      ports:
        - 8087:8087
      networks:
        - vtoolsnet


    traefik:
      # build:
      #   context: .
      #   dockerfile: ./compose/traefik/Dockerfile
      image: traefik:v1.7.16
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/etc/traefik/traefik.toml
        - ./traefik/acme:/etc/traefik/acme
      ports:
       - "80:80"
       - "443:443"
       - "8080:8080"
      networks:
        - vtoolsnet


networks:
  vtoolsnet:
    external: true
